/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2026-01-07T20:20:58.779Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "e90cb51d-17be-4c59-94c9-892e5d61b756",
    name: "Breaking News",
    slug: "breaking-news",
    showInHeader: true,
    showInFooter: true
  }
]
