/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: Trump Tracker
 * Generated: 2026-01-07T20:20:58.779Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "44d581b7-8dba-485e-8c6e-cde34c6b813a",
    name: "Trump Tracker",
    description: "Comprehensive and real-time updates on Donald Trump's activities, statements, and influence in politics and media.",
    url: "https://trump-tracker-blog.vercel.app",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Stay ahead with real-time Trump news and insights"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to Trump Tracker",
    subtitle: "Stay ahead with real-time Trump news and insights"
  },

  // Default author information
  author: {
    name: "Trump Tracker Team",
    bio: "Comprehensive and real-time updates on Donald Trump's activities, statements, and influence in politics and media.",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore News Media Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from Trump Tracker delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Breaking News",
      icon: "Newspaper",
      slug: "breaking-news"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "1336179b-f093-4b0d-9470-7607f9204962",
      name: "Samantha Cruz",
      bio: "Samantha provides a lively and engaging perspective on how Donald Trump intersects with culture and media. Her writing is vibrant and accessible, blending entertainment and analysis to explore Trump's influence beyond politics. Samantha's articles often spark conversation and invite readers to consider the broader cultural implications of his presence.",
      image: "/authors/1336179b-f093-4b0d-9470-7607f9204962.jpg",
      role: "Cultural and Media Commentator"
    },
    {
      id: "0275327a-83c9-49be-9b32-74e3d9f15468",
      name: "Marcus Lee",
      bio: "Marcus thrives in fast-paced environments, delivering real-time updates with accuracy and urgency. Known for his straightforward and clear writing style, Marcus ensures that readers are always informed of the latest developments in Donald Trump's activities, capturing the immediacy and excitement of unfolding events.",
      image: "/authors/0275327a-83c9-49be-9b32-74e3d9f15468.jpg",
      role: "Breaking News Correspondent"
    },
    {
      id: "eeed716d-5f77-4335-8c68-237b95a17ef1",
      name: "Jessica Harper",
      bio: "Jessica possesses an incisive eye for political intricacies, offering readers sharp and insightful analysis of Donald Trump's maneuvers in the political arena. Her writing is characterized by a balanced approach, combining thorough research with a nuanced perspective, ensuring that every article is both informative and thought-provoking.",
      image: "/authors/eeed716d-5f77-4335-8c68-237b95a17ef1.jpg",
      role: "Senior Political Analyst"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#1A73E8",
    secondary: "#FFFFFF",
    accent: "#FF4500"
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#1A73E8",
    secondary: "#FFFFFF",
    accent: "#FF4500"
  }
}
